export const plans = [
  {
    id: 'student',
    name: 'Student',
    description: 'Perfect for students and individual learners',
    price: '$25',
    features: [
      { text: 'Access to all core courses' },
      { text: 'CMRP, CMRT, CAMA preparation' },
      { text: 'Practice exams and quizzes' },
      { text: 'Certificate of completion' },
      { text: 'Mobile app access' },
      { text: 'Email support' },
      { text: '30-day money-back guarantee' },
    ],
    button: {
      text: 'Get Started',
      url: '#',
    },
  },
  {
    id: 'professional',
    name: 'Professional',
    description: 'For serious professionals and small teams',
    price: '$199',
    popular: true,
    features: [
      { text: 'Everything in Student' },
      { text: 'Advanced certification tracks' },
      { text: 'Live webinars and Q&A sessions' },
      { text: 'One-on-one mentoring (2 sessions)' },
      { text: 'Priority support' },
      { text: 'Downloadable resources' },
      { text: 'Progress tracking and analytics' },
      { text: 'Team collaboration tools' },
    ],
    button: {
      text: 'Get Started',
      url: '#',
    },
  },
  {
    id: 'corporate',
    name: 'Corporate',
    description: 'For organizations and large teams',
    price: '$999',
    features: [
      { text: 'Everything in Professional' },
      { text: 'Unlimited team members' },
      { text: 'Custom learning paths' },
      { text: 'Admin dashboard and reporting' },
      { text: 'API access and integrations' },
      { text: 'Dedicated account manager' },
      { text: 'Custom content development' },
      { text: 'On-site training options' },
      { text: 'SLA and priority support' },
    ],
    button: {
      text: 'Contact Sales',
      url: '#',
    },
  },
];
