import { z } from 'zod';

export const membershipSchema = z.object({
  firstName: z.string().min(1, 'Please enter your first name.'),
  lastName: z.string().min(1, 'Please enter your last name.'),
  email: z.string().email('Enter a valid email address.'),
  phone: z.string().optional(),
  company: z.string().min(1, 'Please enter your organization.'),
  role: z.string().min(1, 'Please enter your role/title.'),
  country: z.string().min(1, 'Select your country/region.'),
  experience: z.string().min(1, 'Select your experience band.'),
  industry: z.string().min(1, 'Select your industry.'),
  interests: z.array(z.string()).optional(),
  certs: z.string().optional(),
  referrer: z.string().optional(),
  statement: z.string().min(1, 'Please share a short statement.').max(600, 'Statement should be 600 characters or less.'),
  tier: z.string().min(1, 'Please choose a membership tier.'),
  chapter: z.string().optional(),
  payment: z.string().optional(),
  ethics: z.boolean().refine(val => val === true, 'You must agree to the Code of Ethics.'),
  privacy: z.boolean().refine(val => val === true, 'You must consent to data processing.'),
  news: z.boolean().optional(),
  hpt: z.string().optional(), // Honeypot field
});

export type MembershipFormData = z.infer<typeof membershipSchema>;

export const membershipTiers = [
  'Student',
  'Professional',
  'Corporate (3 seats)',
  'Corporate (10 seats)',
  'Fellow',
  'Lifetime',
] as const;

export const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Other',
] as const;

export const experienceLevels = [
  '0–2',
  '3–5',
  '6–10',
  '11–15',
  '16–20',
  '20+',
] as const;

export const industries = [
  'Power & Water Utilities',
  'Oil & Gas / Petrochemicals',
  'Ports & Terminals / Marine',
  'Manufacturing / FMCG',
  'Mining / Metals',
  'Transportation / Logistics',
  'Consulting / Training',
  'Other',
] as const;

export const professionalInterests = [
  { value: 'RCM', label: 'RCM2/RCM3' },
  { value: 'FMECA', label: 'FMECA' },
  { value: 'APM', label: 'APM / Asset Twins' },
  { value: 'RAM', label: 'RAM / RBD / LCC' },
  { value: 'PdM', label: 'PdM / CM / IIoT' },
  { value: 'ISO55000', label: 'ISO 55000' },
  { value: 'RCA', label: 'RCA / FRACAS' },
  { value: 'Leadership', label: 'Reliability Leadership' },
] as const;

export const referrerOptions = [
  'LinkedIn',
  'Conference / Event',
  'Colleague / Friend',
  'Training / Workshop',
  'Search Engine',
  'Other',
] as const;

export const chapters = [
  'UAE (MENA)',
  'Saudi Arabia',
  'India',
  'Qatar',
  'Oman',
  'Global / Virtual',
] as const;

export const paymentOptions = [
  'Invoice (Bank Transfer)',
  'Card (Stripe)',
  'UPI',
] as const;
