import {
  Award,
  Shield,
  Settings,
  Zap,
  Search,
  BookOpen,
  Wrench,
  Droplets,
  Activity,
  Target,
  AlertTriangle,
  Cog,
  Users,
  BarChart3,
  GraduationCap,
  Car,
  Building2,
} from 'lucide-react';

export const programs = [
  {
    id: 'iam-diploma',
    title: 'IAM Diploma',
    subtitle: 'Institute of Asset Management Diploma',
    icon: Building2,
    level: 'Advanced',
    duration: '150+ hours',
    price: '$5,500',
    description:
      'Master comprehensive strategic asset management principles and practices. Develop expertise in asset lifecycle optimization, risk management, and performance enhancement to become a certified asset management specialist.',
    features: [
      'Strategic Asset Management',
      'Lifecycle Optimization',
      'Risk Management',
      'Performance Measurement',
      'Stakeholder Management',
      'Program Leadership',
    ],
    link: '/programs/iam-diploma',
  },
  {
    id: 'iam-certification',
    title: 'IAM Certification',
    subtitle: 'Institute of Asset Management Certification',
    icon: Building2,
    level: 'Foundation',
    duration: '80+ hours',
    price: '$3,500',
    description:
      'Master fundamental asset management principles and practices. Develop essential skills in asset lifecycle management, risk assessment, and performance optimization to become a certified asset management professional.',
    features: [
      'Asset Management Fundamentals',
      'Lifecycle Management',
      'Risk Assessment',
      'Performance Measurement',
      'Stakeholder Engagement',
      'Program Participation',
    ],
    link: '/programs/iam-certification',
  },
  {
    id: 'rcm2-introductory',
    title: 'RCM2 Introductory Course',
    subtitle: 'Reliability Centered Maintenance Fundamentals',
    icon: Wrench,
    level: 'Foundation',
    duration: '32 hours',
    price: '$1,500',
    description:
      'Master the fundamentals of Reliability Centered Maintenance (RCM2) methodology. Learn to develop effective maintenance strategies that optimize equipment reliability and reduce costs.',
    features: [
      'RCM2 Fundamentals',
      'Failure Analysis',
      'Maintenance Task Selection',
      'RCM2 Implementation',
      'Practical Exercises',
      'Industry Applications',
    ],
    link: '/programs/rcm2-introductory',
  },
  {
    id: 'rcm2-facilitator',
    title: 'RCM2 Facilitator Training',
    subtitle: 'Advanced RCM2 Facilitation Skills',
    icon: Wrench,
    level: 'Advanced',
    duration: '52 hours',
    price: '$2,200',
    description:
      'Become a certified RCM2 facilitator and lead maintenance strategy development initiatives. Master advanced facilitation skills and become an expert in RCM2 program implementation.',
    features: [
      'Advanced RCM2 Theory',
      'Facilitation Skills',
      'Study Management',
      'Complex Applications',
      'Practical Facilitation',
      'Program Leadership',
    ],
    link: '/programs/rcm2-facilitator',
  },
  {
    id: 'vibration-cat1',
    title: 'Vibration Training CAT I',
    subtitle: 'ISO 18436-2 Category I Certification',
    icon: Zap,
    level: 'Foundation',
    duration: '40 hours',
    price: '$1,200',
    description:
      'Master the fundamentals of vibration analysis with our ISO 18436-2 Category I certification program. Learn to collect data, identify basic faults, and start your journey in predictive maintenance.',
    features: [
      'Vibration Fundamentals',
      'Data Collection',
      'Basic Analysis',
      'Equipment Applications',
      'Safety & Standards',
      'Hands-on Training',
    ],
    link: '/programs/vibration-cat1',
  },
  {
    id: 'vibration-cat2',
    title: 'Vibration Training CAT II',
    subtitle: 'ISO 18436-2 Category II Certification',
    icon: Zap,
    level: 'Advanced',
    duration: '60 hours',
    price: '$1,800',
    description:
      'Advance your vibration analysis expertise with our ISO 18436-2 Category II certification program. Master complex fault diagnosis, program leadership, and advanced analysis techniques.',
    features: [
      'Advanced Signal Processing',
      'Complex Fault Diagnosis',
      'Program Management',
      'Advanced Applications',
      'Team Leadership',
      'Expert Training',
    ],
    link: '/programs/vibration-cat2',
  },
  {
    id: 'mla-level1',
    title: 'MLA Level I Training',
    subtitle: 'ISO 18436-4 Machine Lubricant Analyst Level I',
    icon: Droplets,
    level: 'Foundation',
    duration: '44 hours',
    price: '$1,300',
    description:
      'Master the fundamentals of lubricant analysis with our ISO 18436-4 Level I certification program. Learn to perform basic oil analysis, identify contamination, and optimize lubrication programs.',
    features: [
      'Lubrication Fundamentals',
      'Contamination Control',
      'Basic Oil Analysis',
      'Lubricant Selection',
      'Sampling & Documentation',
      'Laboratory Training',
    ],
    link: '/programs/mla-level1',
  },
  {
    id: 'mla-level2',
    title: 'MLA Level II Training',
    subtitle: 'ISO 18436-4 Machine Lubricant Analyst Level II',
    icon: Droplets,
    level: 'Advanced',
    duration: '60 hours',
    price: '$1,900',
    description:
      'Advance your lubricant analysis expertise with our ISO 18436-4 Level II certification program. Master advanced analysis techniques, complex failure diagnosis, and program management.',
    features: [
      'Advanced Lubricant Chemistry',
      'Advanced Analysis Techniques',
      'Failure Analysis',
      'Program Management',
      'Specialized Applications',
      'Expert Training',
    ],
    link: '/programs/mla-level2',
  },
  {
    id: 'mca-level1',
    title: 'MCA Level I Training',
    subtitle: 'Motor Circuit Analysis & Electrical Signature Analysis Level I',
    icon: Activity,
    level: 'Foundation',
    duration: '48 hours',
    price: '$1,400',
    description:
      'Master the fundamentals of motor circuit analysis and electrical signature analysis. Learn to identify electrical faults, diagnose motor problems, and enhance your predictive maintenance capabilities.',
    features: [
      'Electrical Fundamentals',
      'Motor Circuit Analysis',
      'Electrical Signature Analysis',
      'Fault Detection',
      'Testing Procedures',
      'Hands-on Training',
    ],
    link: '/programs/mca-level1',
  },
  {
    id: 'cbm-basic',
    title: 'CBM Basic Level',
    subtitle: 'Condition Based Maintenance for Plant Assets',
    icon: Settings,
    level: 'Foundation',
    duration: '44 hours',
    price: '$1,200',
    description:
      'Master the fundamentals of condition-based maintenance for plant assets. Learn to implement CBM programs, use condition monitoring techniques, and optimize maintenance strategies for better equipment reliability.',
    features: [
      'CBM Fundamentals',
      'Condition Monitoring Techniques',
      'Data Collection & Analysis',
      'CBM Implementation',
      'Maintenance Integration',
      'Practical Applications',
    ],
    link: '/programs/cbm-basic',
  },
  {
    id: 'arp-advocate',
    title: 'ARP-A Certification',
    subtitle: 'Asset Reliability Practitioner - Advocate',
    icon: Target,
    level: 'Foundation',
    duration: '32 hours',
    price: '$1,000',
    description:
      'Become a certified advocate for asset reliability within your organization. Learn to promote reliability culture, communicate effectively about reliability topics, and support reliability improvement initiatives.',
    features: [
      'Reliability Fundamentals',
      'Reliability Analysis',
      'Communication Skills',
      'Reliability Culture',
      'Advocacy Techniques',
      'Team Building',
    ],
    link: '/programs/arp-advocate',
  },
  {
    id: 'arp-engineer',
    title: 'ARP-E Certification',
    subtitle: 'Asset Reliability Practitioner - Engineer',
    icon: Target,
    level: 'Advanced',
    duration: '60 hours',
    price: '$2,000',
    description:
      'Advance your reliability engineering expertise with our ARP-E certification program. Master advanced reliability analysis, program design, and team leadership skills for comprehensive asset reliability management.',
    features: [
      'Advanced Reliability Theory',
      'Reliability Program Design',
      'Advanced Analysis Techniques',
      'Program Management',
      'Specialized Applications',
      'Team Leadership',
    ],
    link: '/programs/arp-engineer',
  },
  {
    id: 'balancing-alignment',
    title: 'Balancing & Alignment',
    subtitle: 'Precision Maintenance Techniques',
    icon: Wrench,
    level: 'Specialist',
    duration: '44 hours',
    price: '$1,300',
    description:
      'Master the art of precision balancing and alignment for rotating equipment. Learn to use advanced equipment and techniques to eliminate vibration problems and optimize machinery performance.',
    features: [
      'Balancing Fundamentals',
      'Alignment Fundamentals',
      'Balancing Equipment',
      'Alignment Equipment',
      'Practical Applications',
      'Quality Control',
    ],
    link: '/programs/balancing-alignment',
  },
  {
    id: 'tuv-functional-safety',
    title: 'TÜV Functional Safety',
    subtitle: 'TÜV RHEINLAND Functional Safety Training',
    icon: AlertTriangle,
    level: 'Expert',
    duration: '56 hours',
    price: '$2,500',
    description:
      'Master functional safety principles and earn internationally recognized TÜV RHEINLAND certification. Learn to design, implement, and manage functional safety systems for critical applications.',
    features: [
      'Functional Safety Fundamentals',
      'Safety Standards & Regulations',
      'Safety System Design',
      'Risk Assessment & Analysis',
      'Implementation & Validation',
      'International Certification',
    ],
    link: '/programs/tuv-functional-safety',
  },
  {
    id: 'mca-level2',
    title: 'MCA Level II Training',
    subtitle: 'Motor Circuit Analysis & Electrical Signature Analysis Level II',
    icon: Activity,
    level: 'Advanced',
    duration: '64 hours',
    price: '$1,800',
    description:
      'Advance your electrical analysis expertise with our Level II certification program. Master complex motor circuit analysis, advanced electrical signature analysis, and program leadership skills.',
    features: [
      'Advanced Electrical Theory',
      'Advanced Circuit Analysis',
      'Advanced Signature Analysis',
      'Complex Fault Diagnosis',
      'Program Management',
      'Expert Training',
    ],
    link: '/programs/mca-level2',
  },
  {
    id: 'rotating-equipment',
    title: 'Rotating Equipment Course',
    subtitle: 'Operation & Maintenance Of Main Rotating Equipment',
    icon: Cog,
    level: 'Specialist',
    duration: '72 hours',
    price: '$1,600',
    description:
      'Master the operation and maintenance of critical rotating equipment including pumps, compressors, turbines, and motors. Learn advanced troubleshooting techniques and optimization strategies.',
    features: [
      'Equipment Fundamentals',
      'Pumps & Compressors',
      'Turbines & Engines',
      'Motors & Generators',
      'Bearings & Seals',
      'Troubleshooting & Diagnostics',
    ],
    link: '/programs/rotating-equipment',
  },
  {
    id: 'cama',
    title: 'CAMA Certification',
    subtitle: 'Certified Asset Management Assessor',
    icon: Award,
    level: 'Expert',
    duration: '8 months',
    price: '$3,200',
    description:
      'The CAMA certification is the highest level credential for asset management professionals. This advanced program covers strategic asset management, risk assessment, and optimization strategies.',
    features: [
      'Asset Management Strategy',
      'Risk Assessment & Mitigation',
      'Performance Metrics & KPIs',
      'Lifecycle Cost Analysis',
      'Asset Optimization Techniques',
      'Regulatory Compliance',
    ],
    link: '/programs/cama',
  },
  {
    id: 'cmrp',
    title: 'CMRP Certification',
    subtitle: 'Certified Maintenance & Reliability Professional',
    icon: Shield,
    level: 'Professional',
    duration: '6 months',
    price: '$2,500',
    description:
      'The CMRP certification is the premier credential for maintenance and reliability professionals. This comprehensive program covers all aspects of maintenance and reliability management.',
    features: [
      'Asset Management Fundamentals',
      'Maintenance Planning & Scheduling',
      'Work Management Systems',
      'Reliability Analysis & Improvement',
      'Maintenance Strategy Development',
      'Performance Measurement & KPIs',
    ],
    link: '/programs/cmrp',
  },
  {
    id: 'cmrt',
    title: 'CMRT Certification',
    subtitle: 'Certified Maintenance & Reliability Technician',
    icon: Settings,
    level: 'Technician',
    duration: '4 months',
    price: '$1,800',
    description:
      'The CMRT certification focuses on hands-on technical skills for maintenance technicians. This program emphasizes practical applications and real-world problem-solving.',
    features: [
      'Preventive Maintenance Strategies',
      'Equipment Troubleshooting Techniques',
      'Safety Protocols & Procedures',
      'Lubrication & Fluid Management',
      'Vibration Analysis Basics',
      'Root Cause Analysis',
    ],
    link: '/programs/cmrt',
  },
  {
    id: 'vibration',
    title: 'Vibration Analysis',
    subtitle: 'ISO 18436 Certified Program',
    icon: Zap,
    level: 'Specialist',
    duration: '3 months',
    price: '$1,200',
    description:
      'Comprehensive vibration analysis training for predictive maintenance applications.',
    features: [
      'Signal Processing',
      'Fault Diagnosis',
      'Machinery Health',
      'Data Analysis',
    ],
    link: '/programs/vibration',
  },
  {
    id: 'thermography',
    title: 'Infrared Thermography',
    subtitle: 'Level I & II Certification',
    icon: Search,
    level: 'Specialist',
    duration: '2 months',
    price: '$900',
    description:
      'Professional thermography training for electrical and mechanical inspections.',
    features: [
      'Thermal Imaging',
      'Heat Patterns',
      'Electrical Inspection',
      'Report Writing',
    ],
    link: '/programs/thermography',
  },
  {
    id: 'lube-oil',
    title: 'Lube Oil Analysis',
    subtitle: 'Tribology & Oil Analysis',
    icon: BookOpen,
    level: 'Specialist',
    duration: '3 months',
    price: '$1,100',
    description:
      'Specialized training in lubricant analysis and tribological principles.',
    features: [
      'Oil Testing',
      'Contamination Analysis',
      'Wear Patterns',
      'Lubrication Programs',
    ],
    link: '/programs/lube-oil',
  },
  {
    id: 'asq-cre',
    title: 'ASQ CRE Certification',
    subtitle: 'Certified Reliability Engineer',
    icon: Cog,
    level: 'Professional',
    duration: '6 months',
    price: '$2,800',
    description:
      'Advanced certification in reliability engineering principles and practices for product and system enhancement. Master performance evaluation and prediction to enhance safety, reliability, and maintainability.',
    features: [
      'Reliability Analysis',
      'Failure Mode Analysis',
      'Reliability Testing',
      'Program Management',
      'Design for Reliability',
      'Lifecycle Management',
    ],
    link: '/programs/asq-cre',
  },
  {
    id: 'prosci-change-management',
    title: 'Prosci Change Management',
    subtitle: 'Certified Change Management Specialist',
    icon: Users,
    level: 'Professional',
    duration: '3-5 days',
    price: '$4,500',
    description:
      "World-class certification program that equips you with tools, expertise, and ongoing support to lead successful organizational change using Prosci's proven methodology and ADKAR Model.",
    features: [
      'ADKAR Model Mastery',
      '3-Phase Process',
      'Change Management Planning',
      'Organizational Change',
      'Project Application',
      'Global Network Access',
    ],
    link: '/programs/prosci-change-management',
  },
  {
    id: 'asset-performance-management',
    title: 'Asset Performance Management',
    subtitle: 'APM Certification',
    icon: BarChart3,
    level: 'Professional',
    duration: '40+ hours',
    price: '$3,200',
    description:
      'Master the art of optimizing asset reliability, availability, and performance while minimizing costs and operational risks. Comprehensive training in APM principles, tools, and implementation strategies.',
    features: [
      'Predictive Maintenance',
      'Asset Optimization',
      'Risk Management',
      'Performance Metrics',
      'Digital APM Tools',
      'Lifecycle Management',
    ],
    link: '/programs/asset-performance-management',
  },
  {
    id: 'diploma-reliability-engineering',
    title: 'Diploma in Reliability Engineering',
    subtitle: 'Advanced Diploma Program',
    icon: GraduationCap,
    level: 'Advanced',
    duration: '120+ hours',
    price: '$4,800',
    description:
      'Comprehensive program covering reliability engineering principles, failure analysis, testing, and system optimization. Master advanced techniques in statistical analysis, reliability modeling, and risk management.',
    features: [
      'Failure Analysis',
      'Statistical Methods',
      'Reliability Testing',
      'System Optimization',
      'Risk Management',
      'Program Management',
    ],
    link: '/programs/diploma-reliability-engineering',
  },
  {
    id: 'certificate-ev-engineering-system-integration',
    title: 'Certificate in EV Engineering',
    subtitle: 'EV Engineering & System Integration',
    icon: Car,
    level: 'Professional',
    duration: '100+ hours',
    price: '$3,500',
    description:
      'Master cutting-edge electric vehicle technologies, battery systems, power electronics, and vehicle integration. Comprehensive training in EV engineering principles and system integration methodologies.',
    features: [
      'Battery Technology',
      'Power Electronics',
      'Vehicle Integration',
      'Charging Systems',
      'Motor Control',
      'Testing & Validation',
    ],
    link: '/programs/certificate-ev-engineering-system-integration',
  },
];
